# Generated by Django 2.1.2 on 2018-12-07 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrelista', models.CharField(blank='false', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(blank='true', max_length=200)),
                ('costoP', models.IntegerField()),
                ('costoR', models.IntegerField()),
                ('notas', models.CharField(blank='true', max_length=200)),
                ('comprado', models.BooleanField(default=False)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedlistas', to='Usuario.Lista')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretienda', models.CharField(blank='false', max_length=200, unique=True)),
                ('nombresucursal', models.CharField(blank='true', max_length=200)),
                ('esOnline', models.BooleanField()),
                ('direccion', models.CharField(blank='true', max_length=200)),
                ('ciudad', models.CharField(blank='true', max_length=200)),
                ('region', models.CharField(blank='true', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Tienda'),
        ),
    ]
