# Generated by Django 2.1.2 on 2018-12-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20181207_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
