# Generated by Django 2.1.2 on 2018-12-12 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_tienda_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatedlistas', to='Usuario.Lista'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.Tienda'),
        ),
    ]
